### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by EASTinphectiON** [httpsoft/http-app#2]
Hey!

Question for ya. 
Think you could Answer this for me Real Quick?
If you don't mind.

First off sorry to create an issue but I'm not sure how else to connect and communicate about the project and goals of creating something more.

I really could use your help.

If you would take me under your wing to help me run this and put it in an emulator to further understand this and visually see what a bunch of code can become.

I've been stuck for days trying to figure out how to do this

Thanks

~EASTinphectiON

**Comment by devanych** [comment]
Hi!

I don't quite understand what you're talking about :) Can you describe in more detail what exactly the question is.
